import type { ApiSuccessResponse } from '../../shared/interfaces/api-response.interface';
import type { CommentAuthorWithStats } from '../comments/comments.interface';
import type { FeedPagePagination, PostComment } from '../feed/feed.interface';

/**
 * Shapes verified against the live API — see docs/api-reference.md > "Notifications
 * endpoints" for the full write-up, generated by real actions between two test accounts
 * (including the two gotchas that would have been easy to get wrong by guessing: a reply
 * notification shares `type: "comment_post"` with a top-level-comment notification, and
 * liking a comment generates no notification at all).
 */

export type NotificationType = 'like_post' | 'comment_post' | 'follow_user' | 'share_post';
export type NotificationEntityType = 'post' | 'comment' | 'user';

export interface NotificationPerson {
  _id: string;
  name: string;
  photo: string;
}

/**
 * `entityType: "post"` — for `like_post`, a top-level `comment_post`, and `share_post` (whose
 * `entityId`/`entity` are the *new share post*, not the original one that got shared).
 * `user` is a bare id string here, unlike every other post shape in this API. `isShare` was
 * observed `false` even on a share post's own entity — don't trust it here.
 */
export interface NotificationPostEntity {
  _id: string;
  body?: string;
  user: string;
  commentsCount: number;
  topComment: PostComment | null;
  sharesCount: number;
  likesCount: number;
  isShare: boolean;
  id: string;
}

/**
 * `entityType: "comment"` — only ever seen on a *reply* notification, where this is the
 * **parent comment that was replied to**, not the new reply itself. There's no direct way to
 * reach the reply's own content from the notification alone.
 */
export interface NotificationCommentEntity {
  _id: string;
  content?: string;
  commentCreator: CommentAuthorWithStats;
  post: string;
  likesCount: number;
  isReply: boolean;
  id: string;
}

/** `entityType: "user"` — for `follow_user`; the new follower's profile. */
export interface NotificationUserEntity {
  _id: string;
  name: string;
  username: string;
  photo: string;
  followersCount: number;
  followingCount: number;
  bookmarksCount: number;
  id: string;
}

export interface AppNotification {
  _id: string;
  recipient: NotificationPerson;
  actor: NotificationPerson;
  type: NotificationType;
  entityType: NotificationEntityType;
  entityId: string;
  isRead: boolean;
  createdAt: string;
  /** Absent (not `null`) until the notification is marked read. */
  readAt?: string;
  entity: NotificationPostEntity | NotificationCommentEntity | NotificationUserEntity;
}

export interface NotificationsListApiResponse extends ApiSuccessResponse<{ notifications: AppNotification[] }> {
  meta: { feedMode: 'page'; pagination: FeedPagePagination };
}

export interface UnreadCountApiResponse extends ApiSuccessResponse<{ unreadCount: number }> {}

export interface MarkNotificationReadApiResponse extends ApiSuccessResponse<{ notification: AppNotification }> {}

export interface MarkAllReadApiResponse extends ApiSuccessResponse<{ modifiedCount: number }> {}
